## erstelle diese Datei in dem Userverzeichnis `~/.aliases`
## `source ~/.aliases` aktuelle Befehle laden

# ls -latr  'drwxr-xr-x 15 user group    4096 Mär 26 10:48' aufsteigend sortiert
alias lls='ls -latrh'

# docker-compose (v1) oder docker compose (v2)
if command -v docker-compose >/dev/null 2>&1; then
  alias dc='docker-compose'
else
  alias dc='docker compose'
fi

## rsr => kopiert Dateien / Ordner in das Ziel, und löscht die Quelle nach erfolg
alias rsr='rsync -avPh --stats --remove-source-files'

##  yml => durchsucht den Inhalt aller yml Files im Verzeichnis "/opt/docker", nach dem folgenden Begriff
alias yml='grep -rnwi --include=\*.yml '/opt/docker/' -e '

## disc usage 1 oder 2 Ebenen mit Sortierung nach Speicherbelegung
alias du1='du -h --max-depth 1 ./ | sort -h'
alias du2='du -h --max-depth 2 ./ | sort -h'
